moodimizer/config/routes.rb
Rails.application.routes.draw do

#user routes
  get '/users' => 'users#index', as: :users
  get '/users/new' => 'users#new', as: :users_new
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :users_edit
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy', as: :users_destroy

#event routes
  get '/events' => 'events#index', as: :events
  get '/events/new' => 'events#new', as: :events_new
  post '/events' => 'events#create'
  get '/events/:id' => 'events#show', as: :event
  get 'events/:id/edit' => 'events#edit', as: :events_edit
  patch 'events/:id' => 'events#update'
  delete 'events/:id' => 'events#destroy', as: :events_destroy

#mood routes
  root 'moods#index'
  get '/moods' => 'moods#index', as: :moods
  get '/moods/:id' => 'moods#show', as: :mood

  # match '/moods/:id/events/new' => 'mood#show', as: :mood


#session routes
  get '/logout' => 'sessions#destroy', as: :logout
  resources :sessions, only: [:new, :create]

end

moodimizer/app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :mood

  # attr_accessor :name, :url
  #
  # validates :name, presence: true, uniqueness: true
  # validates :url, presence: true
  #
  def self.search(search)
    if search.present?
      where('name iLIKE ?', "%#{search}%")
    else
      where(true)
    end
  end
end

moodimizer/app/models/mood.rb
class Mood < ActiveRecord::Base
  has_many :events
  accepts_nested_attributes_for :events
end

moodimizer/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :events, dependent: :destroy
  accepts_nested_attributes_for :events  
end

moodimizer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?, :authorize

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      !current_user.nil?
    end

    def authorize
      unless logged_in?
        redirect_to new_session_path
    end

    def is_current_user?

    end
  end
end

moodimizer/app/controllers/events_controller.rb
class EventsController < ApplicationController

# before_action :authorize, only: [:index, :show]

  def index
    @events = Event.all

    @events = Event.search(params[:search])
    if params[:search]
      @events = Event.search(params[:search]).order("created_at DESC")
    else
      @events = Event.order("created_at DESC")
    end
  end

  def show
    @events = Event.find(params[:id])

    # @user = User.find(params[:id])
  end

  def new
    # @event = Event.new
    @event = current_user.events.build

  end

  def create
    if @event = current_user.events.build(event_params)
        @event.save
      redirect_to events_path
    else
      redirect_to events_new_path
    end
  end

  def edit
    @event = Event.find(params[:id])

  #   if current_user.id == @event.user_id
  #     @event = Event.find(params[:id])
  #   else
  #     redirect_to user_path @user
  # end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to current_user
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
      redirect_to current_user
  end

private
  def event_params
    params.require(:event).permit(:name, :url)
  end
end

moodimizer/app/controllers/moods_controller.rb
class MoodsController < ApplicationController

# before_action :authorize, only: [:index, :show]

  def index
    @moods = Mood.all
  end

  def show
    @mood = Mood.find(params[:id])
  end
end

moodimizer/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by({username: params[:username]})
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome! Thanks #{@user.username} for logging in!"
      redirect_to user_path(@user)
    else
      flash[:failure] = "Oops, something went wrong. Try again."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

moodimizer/app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_action :authorize, only
# :authorize, only:[:edit,:update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Glad you could join us #{@user.username}!"
      redirect_to root_path
    else
      flash[:failure] = "Oops, something went wrong. Try again."
      redirect_to users_new_path
    end
  end

  def edit
    # if current_user.id.to_s == params[:id]
    #   @user = User.find(params[:id])
    # else
    #   redirect_to root_path
    # end


    # if current_user.id.to_s == params[:id]
    #   redirect_to user_path
    # else
      @user = User.find(params[:id])
    # end
    # @user.event.build

  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path @user
    end
  end

  def destroy
    # if current_user.id.to_s == params[:id]
      @user = User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_path @user
    # end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

moodimizer/app/helpers/application_helper.rb
module ApplicationHelper
end

moodimizer/app/helpers/events_helper.rb
module EventsHelper
end

moodimizer/app/helpers/moods_helper.rb
module MoodsHelper
end

moodimizer/app/helpers/sessions_helper.rb
module SessionsHelper
end

moodimizer/app/helpers/users_helper.rb
module UsersHelper
end

moodimizer/app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

<%= form_for @event do |f| %>

	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :url %>
	<%= f.text_area :url, :style => "width: 300px; height: 50px;" %>
  <%= f.submit "Update event", class: "btn btn-large btn-info" %>
<% end %>

<%= link_to 'Cancel', user_path %>

moodimizer/app/views/events/index.html.erb
<br>
<br>
<h1>Events</h1>
<br>
<br>
<%= form_tag(events_path, :method => "get", class: "navbar-form", id: "search-form") do %>
  <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search events" %>
    <button class="btn" type="submit">Search<i class="icon-search"></i></button>
  </div>
<% end %>


<% @events.each do |event| %>
  <hr>
  <ul class="bullets">
    <li><%= link_to event.name, event_path(event) %></li>
  </ul>
<% end %>
<hr>


<br>
<br>
<div class="button-index">
  <%= link_to 'Add an event', events_new_path, class: 'btn' %>
  <%= link_to 'To the mood machine!', moods_path, class: 'btn' %>
  <%= link_to 'Create an account', users_new_path, class: 'btn btn-info' %>
</div>

moodimizer/app/views/events/new.html.erb
<p>Events#new</p>

<div class="container">
<%= form_for(@event) do |e| %>
      <h1 class="form header"><strong>Add an event!</strong></h1>

    <%= e.label :name %>
    <br>
    <%= e.text_field :name %>
		<br>
    <%= e.label :url %>
    <br>
    <%= e.text_field :url %>
    <br>
    <%= e.label :mood_id %>
    <br>
    <%= e.text_field :mood_id %>

    <!-- add mood -->
</div>


<br>
<br>

<div class="container">
  <%= e.submit "Add event", class: "btn btn-large btn-info" %>
  <%= link_to "Cancel", moods_path, class: 'btn btn-primary' %>
</div>

<% end %>

moodimizer/app/views/events/show.html.erb
<br>
<br>
<br>

<div class="entry">
  <h3><strong><%= @events.name %></strong></h3>
  <h4><%= link_to @events.url, "http://#{@events.url}" %></h4>
  <br>
  <p>Posted by: <%= link_to @events.user.username, user_path(@events.user) %></p>
</div>

<hr>

<%= link_to 'Back to events', events_path, class: 'btn btn-info' %>

moodimizer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <title>Moodimizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar right">
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Donate</a></li>
          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Account<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <h6 class="dropdown-header">Account</h6>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a href="#">Login/Logout</a></li>
                <li><a href="#">Settings</a></li>
              </ul> dropdown menu
          </li> dropdown
        </ul>
    </div>
  </header> -->

</head>
<body data-no-turbolink="no">
  <% if logged_in? %>
    <p>Logged in as <strong><%= link_to current_user.username, user_path(current_user) %></strong></p>
    <%= link_to 'Logout', logout_path %>
  <% else %>
    <%= link_to 'Login', new_session_path %>
  <% end %>

  <% if flash[:success] %>
    <div class="alert alert-success"><%= flash[:success] %></div>
  <% elsif flash[:failure] %>
    <div class="alert alert-danger"><%= flash[:failure] %></div>
  <% end %>
  <script>
    $('.alert').delay(2000).slideUp()
  </script>


<div class="container">
  <%= yield %>
</div>


</body>
</html>

moodimizer/app/views/moods/index.html.erb
<br>
<br>
<h2>Feelin'...</h2>


<div class="container">
  <% @moods.each do |m| %>
    <div class="pagination-centered">
      <h3><br><%= link_to (image_tag(m.image)), mood_path(m) %><br><br><%= m.name %></h3>
    </div>
  <% end %>
</div>


<br>
<br>
<br>

<div class="button-index">
  <%= link_to 'Check out all events!', events_path, class: 'btn btn-info' %>
  <%= link_to 'Member Community', users_path, class: 'btn btn-info' %>
  <%= link_to 'Create an account', users_new_path, class: 'btn btn-info' %>
</div>

moodimizer/app/views/moods/show.html.erb
<br>
<br>
<div class="moodnail">
  <p><%= @mood.name %></p>
  <p><%= image_tag(@mood.image) %></p>
</div>

<br>
<br>
<br>


<div class="eventsList">
<hr>
<% @mood.events.each do |m| %>
  <h4><strong><%= link_to m.name, event_path(m) %></strong></h4>
<hr>
<% end %>
</div>



<div class="button-show">
  <hr>
  <%= link_to 'Add an event', events_new_path, class: 'btn btn-success' %>
  <%= link_to 'Back to Moods', moods_path, class: 'btn btn-info' %>
</div>

moodimizer/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_for @user do |f| %>

	<%= f.label :username %>
	<%= f.text_field :username %>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>

  	<%= f.submit "Update Profile", class: "btn btn-large btn-info" %>

<% end %>

<br>
	<%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %>
	<%= link_to 'Cancel', user_path %>

moodimizer/app/views/users/index.html.erb
<br>
<br>
<br>
<h1>Member Community</h1>

<% @users.each do |u| %>
  <h2><%= link_to u.username, user_path(u) %></h2>
  <p>Number of contributed events: <%= u.events.count %></p>
  <hr>
<% end %>

<%= link_to 'Create an account', users_new_path, class: 'btn btn-info' %>

moodimizer/app/views/users/new.html.erb
<h1><strong>MOODIMIZER</strong></h1>

<div class="container">

  <!-- <%= form_tag users_new_path, {:class => 'form-signup'} do |f| %>
  	<div class="row"><legend class="col-md-4 col-md-offset-4">Sign Up</legend></div>
      <fieldset>
	    <div class="form-group">
	        <%= label_tag :username, 'Username', class: 'col-md-4 control-label' %>
		    <div class="col-md-5">
		        <%= text_field_tag :username, params[:username], class: 'form-control' %>
		    </div>
	    </div>
	    <div class="form-group">
	        <%= label_tag :email, 'Email', class: 'col-md-4 control-label' %>
		    <div class="col-md-5">
		        <%= text_field_tag :email, params[:email], class: 'form-control' %>
		    </div>
	    </div>
	    <div class="form-group">
	        <%= label_tag :password, 'Password', class: 'col-md-4 control-label' %>
		    <div class="col-md-5">
		        <%= password_field_tag :password, params[:password], class: 'form-control' %>
		    </div>
	    </div>
	    <div class="form-group">
	        <%= label_tag :password_confirmation, 'Password_confirmation', class: 'col-md-4 control-label' %>
		    <div class="col-md-5">
		        <%= password_field_tag :password_confirmation, params[:password_confirmation], class: 'form-control' %>
		    </div>
	    </div>
    </fieldset>
        <div class="button">
          <%= submit_tag 'Create my account', class: 'btn btn-success' %>
          <%= link_to "Login", new_session_path, class: 'btn btn-info' %>
  	    </div>

  <% end %> -->

<%= form_for @user, :html => {:class=>'form-horizontal'} do |f| %>
<div class="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.submit "Create my account", class: "btn btn-info" %>
</div>
<% end %>

moodimizer/app/views/users/show.html.erb
<br>
<br>
<br>
<h1>Welcome, <%= @user.username %>!</h1>
<h3><%= @user.email %></h3>

<hr>
<br>
<br>
<% @user.events.each do |u| %>
  <ul>
    <li><font size="5"><strong><%= link_to u.name, event_path(u) %></strong></font></li>
    <li><p><%= u.mood_id %></p></li>
  </ul>
<br>
<br>
    <div class="btn-group">
        <%= link_to 'Edit an event', events_edit_path(u), class: "btn btn-primary" %>
    </div>
    <div class="btn-group">
      <%= link_to 'Delete an event', events_destroy_path(u), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger" %>
    </div>
<hr>
<% end %>


<div class="container">
  <div class="btn-group">
    <%= link_to 'Add an event', events_new_path, class: "btn btn-primary" %>
  </div>
  <div class="btn-group">

      <%= link_to 'Edit Profile', users_edit_path, class: "btn btn-primary" %>

  </div>
  <div class="btn-group">
    <%= link_to "HOW YOU FEELIN'?", moods_path, class: "btn btn-large btn-info" %>
  </div>
</div>